export type Guide={slug:string;title:string;description:string;category:string;readingTime:string;intro:string;sections:Array<{heading:string;paragraphs:string[];points?:string[]}>;faq:Array<{question:string;answer:string}>};
export const guides:Guide[]=[
{slug:"ai-receptionist-small-business",title:"AI Receptionist for Small Business: A Practical Guide",description:"Learn what an AI receptionist can handle, where human oversight matters and how a small business can start safely.",category:"Business AI",readingTime:"7 min read",intro:"Small businesses lose opportunities when enquiries arrive after hours, calls go unanswered or follow-ups depend on someone remembering. An AI receptionist can support the first stage of customer communication while the business stays in control.",sections:[
{heading:"What an AI receptionist actually does",paragraphs:["An AI receptionist receives a customer enquiry, identifies what the person needs and responds using information approved by the business. It can collect contact details, answer common questions, suggest appointment times and create a follow-up task.","It should not pretend to know information that the business has not supplied. Prices, availability, policies and commitments need clear sources and a human handoff when the request is uncertain."],points:["Answer frequently asked questions","Capture names, contact details and requirements","Support appointment booking","Organize follow-ups and conversation history"]},
{heading:"Where it creates the most value",paragraphs:["The biggest benefit is consistency. Every new enquiry can receive an immediate acknowledgement, the same essential questions and a visible next step. That matters for service businesses, clinics, real-estate teams, repair companies, consultants and other appointment-led operations.","The goal is not to remove people. It is to reduce repetitive front-desk work so staff can spend more time on customers who need judgment or personal attention."]},
{heading:"How to start without creating complexity",paragraphs:["Begin with one channel and a narrow responsibility. A website enquiry assistant that answers ten common questions and captures qualified leads is easier to test than a system connected to every business tool on day one.","Review real conversations weekly. Add missing information, improve handoff rules and measure response time, captured leads, booked appointments and staff time saved."]}],faq:[{question:"Can an AI receptionist replace staff?",answer:"It is best used to support staff with repetitive enquiries, data capture and scheduling. Complex, sensitive or unusual requests should move to a person."},{question:"Which channel should a small business start with?",answer:"Website chat or business email is usually a controlled first step. Messaging platforms may require business verification and separate platform approval."}]},
{slug:"ai-employee-for-small-business",title:"What Is an AI Employee for a Small Business?",description:"A clear explanation of AI employees, useful workflows, limitations and the best way to introduce one into daily operations.",category:"Automation",readingTime:"8 min read",intro:"An AI employee is not a digital person and it should not operate without boundaries. It is a connected software workspace that can understand routine requests, prepare useful work and carry out approved steps across a business process.",sections:[
{heading:"From separate tools to one workflow",paragraphs:["A normal small-business workflow may involve an inbox, spreadsheet, calendar, notes app and several messaging platforms. Information is copied between them manually, which creates missed follow-ups and incomplete customer records.","An AI employee connects the sequence: receive an enquiry, identify the need, save the lead, propose an appointment and remind the team about the next action."],points:["Customer enquiry assistance","Lead capture and organization","Appointment coordination","Follow-up preparation","Business summaries and task tracking"]},
{heading:"The work that should remain human",paragraphs:["People should remain responsible for decisions involving money, legal commitments, safety, complaints, sensitive personal information and exceptions to business policy. A useful AI system makes escalation easy and keeps activity visible.","Clear permissions are more important than the number of features. A business should know what the system can read, what it can change and when it must ask for approval."]},
{heading:"A practical 30-day rollout",paragraphs:["During the first week, document common enquiries and the correct answers. Next, test lead capture and appointment flows with internal users. In week three, run a limited customer pilot. Use the final week to review accuracy, time saved and missed cases before expanding.","Success should be measured through business outcomes—not the novelty of using AI."]}],faq:[{question:"Is an AI employee the same as a chatbot?",answer:"A chatbot is usually one interface. An AI employee can combine conversation, records, tasks, scheduling and approved actions in a connected workflow."},{question:"Does a business need technical staff?",answer:"A focused hosted product should not require an internal engineering team, although custom integrations may need technical implementation."}]},
{slug:"ai-productivity-for-students",title:"How Students Can Use AI for Planning and Study",description:"Use AI responsibly to organize deadlines, understand notes and create a realistic study plan without outsourcing your learning.",category:"Life Assistant",readingTime:"6 min read",intro:"The most useful student AI is not the one that does every assignment. It is the one that helps a student see the week clearly, understand difficult material and turn scattered deadlines into a realistic plan.",sections:[
{heading:"Build one reliable task system",paragraphs:["Keep assignments, exams, work shifts and personal commitments in one place. Add a due date, category and priority to every important task. An AI planner can then suggest time blocks based on the information you provide.","A good plan includes breaks and leaves space for unexpected work. A packed schedule that cannot survive one delay is not useful."],points:["Capture every deadline","Separate urgent from important","Break large assignments into smaller tasks","Review tomorrow before ending the day"]},
{heading:"Use AI to understand—not to copy",paragraphs:["Paste your own notes and ask for a simpler explanation, key ideas or review questions. Then answer the questions without looking at the summary. This makes AI part of active recall instead of a shortcut around learning.","Check important facts against course material. AI can misunderstand incomplete notes, so it should support your judgment rather than replace it."]},
{heading:"Protect personal and academic information",paragraphs:["Avoid sharing student numbers, passwords, private records or information about other people. Follow the academic-integrity rules for each course and disclose AI use when required.","The best personal assistant stores only what is needed, gives the user control and makes it easy to delete information."]}],faq:[{question:"Can AI create a complete study schedule?",answer:"Yes, when you provide real deadlines, available hours and priorities. You should still review the plan and adjust it to your energy and course requirements."},{question:"Should students submit AI-written assignments?",answer:"Students should follow their institution and instructor policies. AI is safer for explanation, planning, brainstorming and review than for replacing assessed work."}]}
];
export function getGuide(slug:string){return guides.find(guide=>guide.slug===slug)}
